### ISSUE TITLE
Multiline scripts.

### ISSUE THREAD

**Issue by bartoszek** [bartoszek/arch-travis#1]
current `travis_yaml()` read function doesn't distinguish multiline script from single-line ones. 
```yml
arch:
  script:
  - sudo screenfetch
  - reflector --verbose -l 20 --sort rate -p https
  - echo $CC
  - touch test_file
  - |
    for ((i=0;i<10;i++)) ; do
      echo test$i
    done
```
`yq .arch.script .travis.yml`
```json
[
  "sudo screenfetch",
  "reflector --verbose -l 20 --sort rate -p https",
  "echo $CC",
  "touch test_file",
  "for ((i=0;i<10;i++)) ; do\n  echo test$i\ndone\n"
]
```
`ruby -ryaml -e 'puts ARGV[1..-1].inject(YAML.load(File.read(ARGV[0]))) {|acc, key| acc[key] }' .travis.yml arch script`
```
sudo screenfetch
reflector --verbose -l 20 --sort rate -p https
echo $CC
touch test_file
for ((i=0;i<10;i++)) ; do
  echo test$i
done
```
Solutions:
- [x] fix `ruby` scirpt
- [ ] use `yq` or directly `python:yml` to load `.travis.yml`
